[package]
name = "gitsecal"
version = "0.1.0"
authors = ["jerith <firxen@gmail.com>"]
edition = "2018"

[dependencies]

failure = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
graphql_client = "0.8"
reqwest = "^0.9.0"
prettytable-rs = "0.7.0"
structopt = "0.2"